### ISSUE TITLE
/traveltocrossroads did not work for me

### ISSUE THREAD

**Issue by wstathis** [plerpsandplerps/AnnouncerBot#32]
Got "you travelled" message, but still in farmland aftewards

**Comment by wstathis** [comment]
![image](https://user-images.githubusercontent.com/62320087/189510906-5fba25f1-cb6d-4a96-90b1-5d09ebfe4020.png)
![image](https://user-images.githubusercontent.com/62320087/189510909-bc80b7d2-51ba-4c90-b229-6229e10b3814.png)

**Comment by plerpsandplerps** [comment]
@wstathis this seems to be closed with your branch
