### ISSUE TITLE
Got damaged by interrupt while no longer on cooldown

### ISSUE THREAD

**Issue by wstathis** [plerpsandplerps/AnnouncerBot#33]

**Comment by wstathis** [comment]
![image](https://user-images.githubusercontent.com/62320087/189510940-e0966e22-ef3d-4b4b-b741-fca83569234f.png)
![image](https://user-images.githubusercontent.com/62320087/189510946-0b78b704-a4b5-4155-b492-244ff2727aa3.png)

**Comment by plerpsandplerps** [comment]
currently evade/rest sets `evade: true` on players.json which is then replaced by false when the player takes their next action. 

probably better to just do a `lastactiontime: epochtime` combined with the existing `lastaction` field to handle any durations in the game (remove the evade and rest fields)
